language: python
sudo: false

matrix:
  include:
    - python: 3.4
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=py
    - python: 3.6
      env: TOXENV=py

    - python: 3.4
      env: TOXENV=cov
      before_script: pip install -U coveralls
      after_success: coveralls

install: pip install -U tox
script: tox -v
